baseurl = "https://dpsg-radolfzell.de/"
title = "DPSG Stamm Impeesa"
languageCode = "de-DE"
DefaultContentLanguage = "de"
enableGitInfo = false
theme = []

[permalinks]
  news = "/news/:slug-:year"
 
# [Author] # Used in authorbox
#   name = "Scout Master"
#   bio = "The Scout Master is the leader of this local scout group"
#   avatar = "img/avatar.png"

[pagination]
  pagerSize  = "5" # Number of posts per page
  disableAliases = false
  path = ''

[Params]
  description = "Die Seite die niemals schläft" # Site description. Used in meta description
  copyright = "DPSG Stamm Impeesa Radolfzell e.V." # Footer copyright holder, otherwise will use site title
  thumbnail = "/img/banner.webp"
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = false # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  indexPager = false # Show pager navigation on index page
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02.01.2006" # Change the format of dates
  selfHosted = true # Use self-hosted fonts/js/css if true
  progressive_webapp = false # Enable Progressive Web App if true
  # customPartial = "plausible.html" # Custom partial to include in head
  expanded_menu = false # always show menu items in expanded mode on mobile
  start_button = true # show dpsg logo button in menu bar that links to the index page
  darkmode = false

[Params.style.vars]
  highlightColor = "#003056" # Override main theme color

[Params.logo]
  image = "/img/logo.webp" # Logo image. Path relative to "static"
  header = "/img/header.webp" # Header image. Path relative to "static"
  title = "DPSG Stamm Impeesa" # Logo title, otherwise will use site title
  subtitle = "Radolfzell/Markelfingen" # Logo subtitle
  image_alt = "DPSG Stamm Impeesa Radolfzell e.V. logo" # Logo alt text

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["local-search","recent", "categories", "taglist", "social"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.footer]
  # text = "[Impressum und Datenschutz](/impressum/)" # Extra text in footer row, understands markdown
  right = "[Impressum](/impressum/) [Datenschutzerklärung](/datenschutz/)" # Right-aligned text in footer row, understands markdown



[Params.widgets.social]
  # Enable parts of social widget
  facebook = "dpsg.radolfzell.de"
  # twitter = "username"
  instagram = "dpsg_stamm_impeesa"
  # linkedin = "username"
  # elegram = "username"
  # github = "dpsg-impeesa"
  # gitlab = "username"
  # bitbucket = "username"
  # email = "info@dpsg-radolfzell.de"
  rss = "/news/index.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true



[outputs]
  home = ["HTML", "RSS", "JSON"]

[module]
[[module.imports]]
    path = 'github.com/emhl/hugo-dpsg'
[[module.imports]]
    path = 'github.com/emhl/hugo-photoswipe-gallery'
