name: Deploy website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Fetch more commits
        run: git fetch --unshallow

      - name: Build website
        run: hugo  --gc --minify
      
      - name: Update calendar
        run: public/kalender/get-calendars.sh

      - name: Setup IndexNow 
        run: echo ${{ secrets.INDEXNOW_KEY }} > public/${{ secrets.INDEXNOW_KEY }}.txt

      - name: Copy website to host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          local-dir: './public/'
        
      - name: Indexnow Sitemap
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://dpsg-radolfzell.de/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          lastmod-required: false

      - name: Indexnow RSS
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://dpsg-radolfzell.de/index.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          lastmod-required: false
